# Generated by Django 4.1.2 on 2022-10-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('planTO', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planTraffic', models.IntegerField()),
                ('planNum', models.IntegerField()),
                ('factTO', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factTraffic', models.IntegerField()),
                ('factNum', models.IntegerField()),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shop')),
            ],
        ),
    ]
